// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: service/dbproxy/proto/dbproxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params []byte `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // 请求参数列表, json-encoded
}

func (x *SingleAction) Reset() {
	*x = SingleAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dbproxy_proto_dbproxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleAction) ProtoMessage() {}

func (x *SingleAction) ProtoReflect() protoreflect.Message {
	mi := &file_service_dbproxy_proto_dbproxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleAction.ProtoReflect.Descriptor instead.
func (*SingleAction) Descriptor() ([]byte, []int) {
	return file_service_dbproxy_proto_dbproxy_proto_rawDescGZIP(), []int{0}
}

func (x *SingleAction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SingleAction) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence    bool            `protobuf:"varint,1,opt,name=Sequence,proto3" json:"Sequence,omitempty"`       //是否是串行化
	Transaction bool            `protobuf:"varint,2,opt,name=Transaction,proto3" json:"Transaction,omitempty"` //是否是事务
	ResultType  int32           `protobuf:"varint,3,opt,name=resultType,proto3" json:"resultType,omitempty"`   // 0表示每个sql函数的结果都返回; 1表示只返回最后一个执行sql的结果(要求sequence执行)
	Action      []*SingleAction `protobuf:"bytes,4,rep,name=action,proto3" json:"action,omitempty"`
}

func (x *ExecReq) Reset() {
	*x = ExecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dbproxy_proto_dbproxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecReq) ProtoMessage() {}

func (x *ExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_dbproxy_proto_dbproxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecReq.ProtoReflect.Descriptor instead.
func (*ExecReq) Descriptor() ([]byte, []int) {
	return file_service_dbproxy_proto_dbproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ExecReq) GetSequence() bool {
	if x != nil {
		return x.Sequence
	}
	return false
}

func (x *ExecReq) GetTransaction() bool {
	if x != nil {
		return x.Transaction
	}
	return false
}

func (x *ExecReq) GetResultType() int32 {
	if x != nil {
		return x.ResultType
	}
	return 0
}

func (x *ExecReq) GetAction() []*SingleAction {
	if x != nil {
		return x.Action
	}
	return nil
}

//网络式resp 通过json包将信息复原到struct
type ExecResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coede   int32  `protobuf:"varint,1,opt,name=coede,proto3" json:"coede,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExecResp) Reset() {
	*x = ExecResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dbproxy_proto_dbproxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResp) ProtoMessage() {}

func (x *ExecResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_dbproxy_proto_dbproxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResp.ProtoReflect.Descriptor instead.
func (*ExecResp) Descriptor() ([]byte, []int) {
	return file_service_dbproxy_proto_dbproxy_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResp) GetCoede() int32 {
	if x != nil {
		return x.Coede
	}
	return 0
}

func (x *ExecResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_service_dbproxy_proto_dbproxy_proto protoreflect.FileDescriptor

var file_service_dbproxy_proto_dbproxy_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x8e, 0x01, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x65, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x65, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x33, 0x0a, 0x0e, 0x44, 0x42, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x08, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_dbproxy_proto_dbproxy_proto_rawDescOnce sync.Once
	file_service_dbproxy_proto_dbproxy_proto_rawDescData = file_service_dbproxy_proto_dbproxy_proto_rawDesc
)

func file_service_dbproxy_proto_dbproxy_proto_rawDescGZIP() []byte {
	file_service_dbproxy_proto_dbproxy_proto_rawDescOnce.Do(func() {
		file_service_dbproxy_proto_dbproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_dbproxy_proto_dbproxy_proto_rawDescData)
	})
	return file_service_dbproxy_proto_dbproxy_proto_rawDescData
}

var file_service_dbproxy_proto_dbproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_dbproxy_proto_dbproxy_proto_goTypes = []interface{}{
	(*SingleAction)(nil), // 0: SingleAction
	(*ExecReq)(nil),      // 1: ExecReq
	(*ExecResp)(nil),     // 2: ExecResp
}
var file_service_dbproxy_proto_dbproxy_proto_depIdxs = []int32{
	0, // 0: ExecReq.action:type_name -> SingleAction
	1, // 1: DBProxyService.ExecAction:input_type -> ExecReq
	2, // 2: DBProxyService.ExecAction:output_type -> ExecResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_dbproxy_proto_dbproxy_proto_init() }
func file_service_dbproxy_proto_dbproxy_proto_init() {
	if File_service_dbproxy_proto_dbproxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_dbproxy_proto_dbproxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dbproxy_proto_dbproxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dbproxy_proto_dbproxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_dbproxy_proto_dbproxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_dbproxy_proto_dbproxy_proto_goTypes,
		DependencyIndexes: file_service_dbproxy_proto_dbproxy_proto_depIdxs,
		MessageInfos:      file_service_dbproxy_proto_dbproxy_proto_msgTypes,
	}.Build()
	File_service_dbproxy_proto_dbproxy_proto = out.File
	file_service_dbproxy_proto_dbproxy_proto_rawDesc = nil
	file_service_dbproxy_proto_dbproxy_proto_goTypes = nil
	file_service_dbproxy_proto_dbproxy_proto_depIdxs = nil
}
